export const rows = [
  {
    id: 1,
    carImage: '2.png',
    carName: 'VolksWagen',
    carPrice: 23896.35,
    carMake: 'Volks Wagen',
    carModel: 'X-4',
    carYear: '2020',
    carRevenue: 234,
    carCurrency: '$',
    trips: 50,
    rating: 4.5,
    inspecturoScore: 60,
    owner: 'Jacob',
    ownerTrips: 70,
    ownerRating: 3.4,
    fuelType: 'DIESEL',
    doors: 4,
    description: 'Very Good'
  },
  {
    id: 2,
    carImage: '1.png',
    carName: 'Toyoto',
    carPrice: 23896.35,
    carMake: 'Toyota Company',
    carModel: 'X-4',
    carRevenue: 234,
    carYear: '2021',
    carCurrency: '$',
    trips: 20,
    rating: 4.9,
    inspecturoScore: 25,
    owner: 'Roberto',
    ownerTrips: 30,
    ownerRating: 4.4,
    fuelType: 'ELECTRIC',
    doors: 4,
    description: 'Awesome'
  }
]
